/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aman
 */
public class Length extends javax.swing.JFrame {

    /**
     * Creates new form Length
     */
    public Length() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        from = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        to = new javax.swing.JComboBox();
        x = new javax.swing.JTextField();
        y = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("    Length Converter");

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel2.setText("        From");

        from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meter", "Centimeter", "Kilometer", "Mile", "Foot", "Inch" }));

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel3.setText("         To");

        to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Meter", "Centimeter", "Kilometer", "Mile", "Foot", "Inch" }));

        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        x.setText(null);
        y.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.toBack();
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double z;
        double value = Double.parseDouble(x.getText());
        if (from.getSelectedItem().toString() == "Meter" && to.getSelectedItem().toString() == "Meter") {
            z = value;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Meter" && to.getSelectedItem().toString() == "Centimeter") {
            z = value * 100;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Meter" && to.getSelectedItem().toString() == "Kilometer") {
            z = value / 1000;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Meter" && to.getSelectedItem().toString() == "Mile") {
            z = value / 1609;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Meter" && to.getSelectedItem().toString() == "Foot") {
            z = value * 3.281;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Meter" && to.getSelectedItem().toString() == "Inch") {
            z = value * 39.37;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Centimeter" && to.getSelectedItem().toString() == "Meter") {
            z = value / 100;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Centimeter" && to.getSelectedItem().toString() == "Centimeter") {
            z = value;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Centimeter" && to.getSelectedItem().toString() == "Kilometer") {
            z = value / 100000;
            y.setText(String.format("%.3f", z));
    }//GEN-LAST:event_jButton1ActionPerformed
        else if (from.getSelectedItem().toString() == "Centimeter" && to.getSelectedItem().toString() == "Mile") {
            z = value / 160900;
            y.setText(String.format("%.3f", z));

        } else if (from.getSelectedItem().toString() == "Centimeter" && to.getSelectedItem().toString() == "Foot") {
            z = value / 30.48;
            y.setText(String.format("%.3f", z));

        } else if (from.getSelectedItem().toString() == "Centimeter" && to.getSelectedItem().toString() == "Inch") {
            z = value / 2.54;
            y.setText(String.format("%.3f", z));

        } else if (from.getSelectedItem().toString() == "Kilometer" && to.getSelectedItem().toString() == "Meter") {
            z = value * 1000;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Kilometer" && to.getSelectedItem().toString() == "Centimeter") {
            z = value * 100000;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Kilometer" && to.getSelectedItem().toString() == "Kilometer") {
            z = value;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Kilometer" && to.getSelectedItem().toString() == "Mile") {
            z = value / 1.609;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Kilometer" && to.getSelectedItem().toString() == "Foot") {
            z = value * 3281;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Kilometer" && to.getSelectedItem().toString() == "Inch") {
            z = value * 39370;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Mile" && to.getSelectedItem().toString() == "Meter") {
            z = value * 1609;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Mile" && to.getSelectedItem().toString() == "Centimeter") {
            z = value * 160900;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Mile" && to.getSelectedItem().toString() == "Kilometer") {
            z = value * 1.609;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Mile" && to.getSelectedItem().toString() == "Mile") {
            z = value;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Mile" && to.getSelectedItem().toString() == "Foot") {
            z = value * 5280;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Mile" && to.getSelectedItem().toString() == "Inch") {
            z = value * 63360;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Foot" && to.getSelectedItem().toString() == "Meter") {
            z = value / 3.281;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Foot" && to.getSelectedItem().toString() == "Centimeter") {
            z = value * 30.48;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Foot" && to.getSelectedItem().toString() == "Kilometer") {
            z = value / 3281;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Foot" && to.getSelectedItem().toString() == "Mile") {
            z = value / 5280;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Foot" && to.getSelectedItem().toString() == "Foot") {
            z = value;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Foot" && to.getSelectedItem().toString() == "Inch") {
            z = value * 12;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Inch" && to.getSelectedItem().toString() == "Meter") {
            z = value / 39.37;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Inch" && to.getSelectedItem().toString() == "Centimeter") {
            z = value * 2.54;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Inch" && to.getSelectedItem().toString() == "Kilometer") {
            z = value / 39370;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Inch" && to.getSelectedItem().toString() == "Mile") {
            z = value / 63360;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Inch" && to.getSelectedItem().toString() == "Foot") {
            z = value / 12;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Inch" && to.getSelectedItem().toString() == "Inch") {
            z = value;
            y.setText(String.format("%.3f", z));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Length.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Length().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox to;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
