/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aman
 */
public class Time extends javax.swing.JFrame {

    /**
     * Creates new form Time
     */
    public Time() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        from = new javax.swing.JComboBox();
        x = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        to = new javax.swing.JComboBox();
        y = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("  Time Converter");

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel2.setText("     From");

        from.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Second", "Minute", "Hour", "Day", "Week", "Month", "Year" }));

        x.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jLabel3.setText("      To");

        to.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Second", "Minute", "Hour", "Day", "Week", "Month", "Year" }));

        jButton1.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton4.setText("Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(from, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(to, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(x)
                                    .addComponent(y, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(y, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        double z;
        double value = Double.parseDouble(x.getText());
        if (from.getSelectedItem().toString() == "Second" && to.getSelectedItem().toString() == "Second") {
            z = value;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Second" && to.getSelectedItem().toString() == "Minute") {
            z = value * 0.0166667;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Second" && to.getSelectedItem().toString() == "Hour") {
            z = value / 3600;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Second" && to.getSelectedItem().toString() == "Day") {
            z = value / 86400;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Second" && to.getSelectedItem().toString() == "Week") {
            z = value / 604800;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Second" && to.getSelectedItem().toString() == "Month") {
            z = value / 2.628e+6;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Second" && to.getSelectedItem().toString() == "Year") {
            z = value / 3.154e+7;
            y.setText(String.format("%.3f", z));
        } else if (from.getSelectedItem().toString() == "Minute" && to.getSelectedItem().toString() == "Second") {
            z = value * 60;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Minute" && to.getSelectedItem().toString() == "Minute") {
            z = value;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Minute" && to.getSelectedItem().toString() == "Hour") {
            z = value / 60;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Minute" && to.getSelectedItem().toString() == "Day") {
            z = value / 1440;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Minute" && to.getSelectedItem().toString() == "Week") {
            z = value / 10080;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Minute" && to.getSelectedItem().toString() == "Month") {
            z = value / 43800;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Minute" && to.getSelectedItem().toString() == "Year") {
            z = value / 525600;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Hour" && to.getSelectedItem().toString() == "Second") {
            z = value * 3600;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Hour" && to.getSelectedItem().toString() == "Minute") {
            z = value * 60;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Hour" && to.getSelectedItem().toString() == "Hour") {
            z = value;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Hour" && to.getSelectedItem().toString() == "Day") {
            z = value / 24;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Hour" && to.getSelectedItem().toString() == "Week") {
            z = value / 168;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Hour" && to.getSelectedItem().toString() == "Month") {
            z = value / 730;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Hour" && to.getSelectedItem().toString() == "Year") {
            z = value / 8760;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Day" && to.getSelectedItem().toString() == "Second") {
            z = value * 86400;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Day" && to.getSelectedItem().toString() == "Minute") {
            z = value * 1440;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Day" && to.getSelectedItem().toString() == "Hour") {
            z = value * 24;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Day" && to.getSelectedItem().toString() == "Day") {
            z = value;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Day" && to.getSelectedItem().toString() == "Week") {
            z = value / 7;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Day" && to.getSelectedItem().toString() == "Month") {
            z = value / 30.417;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Day" && to.getSelectedItem().toString() == "Year") {
            z = value / 365;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Week" && to.getSelectedItem().toString() == "Second") {
            z = value * 604800;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Week" && to.getSelectedItem().toString() == "Minute") {
            z = value * 10080;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Week" && to.getSelectedItem().toString() == "Hour") {
            z = value * 168;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Week" && to.getSelectedItem().toString() == "Day") {
            z = value * 7;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Week" && to.getSelectedItem().toString() == "Week") {
            z = value;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Week" && to.getSelectedItem().toString() == "Month") {
            z = value / 4.345;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Week" && to.getSelectedItem().toString() == "Year") {
            z = value / 52.143;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Month" && to.getSelectedItem().toString() == "Second") {
            z = value * 2.628e+6;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Month" && to.getSelectedItem().toString() == "Minute") {
            z = value * 43800;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Month" && to.getSelectedItem().toString() == "Hour") {
            z = value * 730;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Month" && to.getSelectedItem().toString() == "Day") {
            z = value * 30.417;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Month" && to.getSelectedItem().toString() == "Week") {
            z = value * 4.345;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Month" && to.getSelectedItem().toString() == "Month") {
            z = value;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Month" && to.getSelectedItem().toString() == "Year") {
            z = value / 12;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Year" && to.getSelectedItem().toString() == "Second") {
            z = value * 3.154e+7;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Year" && to.getSelectedItem().toString() == "Minute") {
            z = value * 525600;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Year" && to.getSelectedItem().toString() == "Hour") {
            z = value * 8760;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Year" && to.getSelectedItem().toString() == "Day") {
            z = value * 365;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Year" && to.getSelectedItem().toString() == "Week") {
            z = value * 52.143;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Year" && to.getSelectedItem().toString() == "Month") {
            z = value * 12;
            y.setText("" + z);
        } else if (from.getSelectedItem().toString() == "Year" && to.getSelectedItem().toString() == "Year") {
            z = value;
            y.setText("" + z);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        x.setText(null);
        y.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.toBack();
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Time.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Time().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox from;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox to;
    private javax.swing.JTextField x;
    private javax.swing.JTextField y;
    // End of variables declaration//GEN-END:variables
}
